// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidBootcamp.ReverseEF.DatabaseCF;

public partial class Customer
{
    [Key]
    public int CustomerId { get; set; }

    [Required]
    [StringLength(255)]
    public string CustomerName { get; set; }

    [Required]
    public string Email { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<OrderHeader> OrderHeaders { get; set; } = new List<OrderHeader>();
}