// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidBootcamp.ReverseEF.DatabaseCF;

[Index("CustomerId", Name = "IX_OrderHeaders_CustomerId")]
public partial class OrderHeader
{
    [Key]
    public string OrderHeaderId { get; set; }

    public int CustomerId { get; set; }

    public DateTime TransactionDate { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("OrderHeaders")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("OrderHeader")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}