// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidBootcamp.ETLSample.DbDataWarehouse;

[Table("Dim_Product")]
public partial class DimProduct
{
    [Key]
    public int ProductId { get; set; }

    public int ProductOriginalKey { get; set; }

    [Required]
    [StringLength(255)]
    public string ProductName { get; set; }

    [Required]
    [StringLength(255)]
    public string CategoryName { get; set; }

    public int Stock { get; set; }

    [Column(TypeName = "money")]
    public decimal Price { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<FactSale> FactSales { get; set; } = new List<FactSale>();
}