// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidBootcamp.ETLSample.DbDataWarehouse;

[Table("Dim_Wallet")]
public partial class DimWallet
{
    [Key]
    public int WalletId { get; set; }

    public int? WalletOriginalKey { get; set; }

    [StringLength(255)]
    public string CustomerName { get; set; }

    [StringLength(255)]
    public string CustomerEmail { get; set; }

    [StringLength(255)]
    public string WalletTypeName { get; set; }

    [Column(TypeName = "money")]
    public decimal Saldo { get; set; }

    [InverseProperty("Wallet")]
    public virtual ICollection<FactSale> FactSales { get; set; } = new List<FactSale>();
}