// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidBootcamp.ETLSample.DbDataWarehouse;

[Table("Fact_Sales")]
public partial class FactSale
{
    [Key]
    public int SalesId { get; set; }

    public int? ProductId { get; set; }

    public int? WalletId { get; set; }

    [StringLength(8)]
    [Unicode(false)]
    public string OrderHeaderId { get; set; }

    public int? OrderDetailOriginalId { get; set; }

    public int Qty { get; set; }

    [Column(TypeName = "money")]
    public decimal Price { get; set; }

    [Column(TypeName = "money")]
    public decimal TotalSales { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("FactSales")]
    public virtual DimProduct Product { get; set; }

    [ForeignKey("WalletId")]
    [InverseProperty("FactSales")]
    public virtual DimWallet Wallet { get; set; }
}