// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RapidBootcamp.ETLSample.DbDataWarehouse;

public partial class RapidDbContext : DbContext
{

    public virtual DbSet<DimProduct> DimProducts { get; set; }

    public virtual DbSet<DimWallet> DimWallets { get; set; }

    public virtual DbSet<FactSale> FactSales { get; set; }

    override protected void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        //add connection string here
        optionsBuilder.UseSqlServer("Server=.;Database=RapidDW;Trusted_Connection=True;TrustServerCertificate=True;");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DimProduct>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK_Dim_Products");
        });

        modelBuilder.Entity<FactSale>(entity =>
        {
            entity.Property(e => e.OrderHeaderId).IsFixedLength();

            entity.HasOne(d => d.Product).WithMany(p => p.FactSales).HasConstraintName("FK_Fact_Sales_Dim_Product");

            entity.HasOne(d => d.Wallet).WithMany(p => p.FactSales).HasConstraintName("FK_Fact_Sales_Dim_Wallet");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}