// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidBootcamp.ReverseEF.Models;

public partial class WalletType
{
    [Key]
    public int WalletTypeId { get; set; }

    [Required]
    [StringLength(255)]
    public string WalletName { get; set; }

    [InverseProperty("WalletType")]
    public virtual ICollection<Wallet> Wallets { get; set; } = new List<Wallet>();
}