// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidBootcamp.ETLSample.DbTransactional;

public partial class OrderHeader
{
    [Key]
    [StringLength(8)]
    [Unicode(false)]
    public string OrderHeaderId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime TransactionDate { get; set; }

    public int WalletId { get; set; }

    [InverseProperty("OrderHeader")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [ForeignKey("WalletId")]
    [InverseProperty("OrderHeaders")]
    public virtual Wallet Wallet { get; set; }
}