// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RapidBootcamp.ETLSample.DbTransactional;

public partial class Wallet
{
    [Key]
    public int WalletId { get; set; }

    public int CustomerId { get; set; }

    public int WalletTypeId { get; set; }

    [Column(TypeName = "money")]
    public decimal Saldo { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Wallets")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Wallet")]
    public virtual ICollection<OrderHeader> OrderHeaders { get; set; } = new List<OrderHeader>();

    [ForeignKey("WalletTypeId")]
    [InverseProperty("Wallets")]
    public virtual WalletType WalletType { get; set; }
}